[".zsh/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
    [".zsh/zsh-autosuggestions".pull]
        args = ["--ff-only"]

[".zsh/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
    [".zsh/zsh-syntax-highlighting".pull]
        args = ["--ff-only"]

[".zsh/zsh-completions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-completions.git"
    refreshPeriod = "168h"
    [".zsh/zsh-completions".pull]
        args = ["--ff-only"]
