tap "alexnabokikh/tfsort"
tap "cowsay-org/cowsay"
tap "homebrew/bundle"
tap "homebrew/services"
brew "awscli"
brew "checkov"
brew "chezmoi"
brew "cowsay"
brew "defaultbrowser"
brew "figlet"
brew "fortune"
brew "gh"
brew "pinentry"
brew "gnupg"
brew "lolcat"
brew "mas"
brew "mise"
brew "neovim"
brew "pinentry-mac"
brew "pre-commit"
brew "starship"
brew "alexnabokikh/tfsort/tfsort"
cask "1password"
cask "amethyst"
cask "brave-browser"
cask "diffmerge"
cask "docker"
cask "grammarly-desktop"
cask "iterm2"
cask "keybase"
cask "yubico-yubikey-manager"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Numbers", id: 409203825
