[tools]
cosign = "latest"
infracost = "latest"
node = "latest"
python = "latest"
ruby = "latest"
terraform = "latest"
terraform-docs = "latest"
terragrunt = "latest"
terrascan = "latest"
tflint = "latest"
